### ISSUE TITLE
server host hardcoded to 'marine' should be 'localhost' and port 2000, 

### ISSUE THREAD

**Issue by chris-redfield** [carlanet/pycarlanet#1]
Hi ! 
This project seems inactive for a while, but I just want to give a small contribution as I'm trying to reuse pycarlanet for my research, I had two problems trying to run the sample code:
1. host and port different than a default value are set in here: https://github.com/carlanet/pycarlanet/blob/main/example/car_light_control/main.py#L211 I suggest changing it to 'localhost' and port '2000' as 2000 is the default port when running carla
2. also, WORLD01 does not exist at carla 0.9.13 linux instalation, I figured it would be TOWN01 as I saw that at the hd maps folder

After I made these 2 changes, I was able to run the car light control sample

Thanks!
**edit**: Great code by the way, I've been able to do small traffic monitoring experiments with data collected from agents 
![heavy-traffic](https://github.com/carlanet/pycarlanet/assets/1541692/53cf04bd-d1ae-4ee0-b95c-afe3ba2769ec)

**Comment by christianquadri** [comment]
Thank you for your message.
We have just started a long process of revising and refactoring both carlanet components and we are going to fix hardcoded strings.

Thanks

**Comment by jaivra** [comment]
Hi,
Thanks for your bug report. The issue should now be fixed with [a8ee1b5796d0db52e5c474a498513401d962da74](https://github.com/carlanet/pycarlanet/commit/a8ee1b5796d0db52e5c474a498513401d962da74)

If you have any further suggestions or feedback, please share them with us, or even better, propose fixes/solutions directly through pull requests.

Cheers,
Valerio
